name: CI

on:
  push:
    paths:
      - .github/workflows/ronin-install.yml
      - Makefile
      - ronin-install.sh
      - test/helper.sh
      - test/ronin_install_test.sh
  pull_request:
    paths:
      - .github/workflows/ronin-install.yml
      - Makefile
      - ronin-install.sh
      - test/helper.sh
      - test/ronin_install_test.sh

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: "ronin-install.sh on Ubuntu"
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update -qq -y && sudo apt-get install -qq -y shunit2
      - name: Configure env
        run: echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
      - name: Run tests
        run: ./test/ronin_install_test.sh

  fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    name: "ronin-install.sh on Fedora Linux"
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dnf update -q -y && dnf install -q -y shunit2
      - name: Configure env
        run: echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
      - name: Run tests
        run: ./test/ronin_install_test.sh

  opensuse:
    runs-on: ubuntu-latest
    container: opensuse:latest
    name: "ronin-install.sh on OpenSUSE"
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: zypper ref && zypper --non-interactive in shunit2
      - name: Configure env
        run: echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
      - name: Run tests
        run: ./test/ronin_install_test.sh

  archlinux:
    runs-on: ubuntu-latest
    container: archlinux:latest
    name: "ronin-install.sh on ArchLinux"
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pacman -Syu && pacman -S shunit2
      - name: Configure env
        run: echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
      - name: Run tests
        run: ./test/ronin_install_test.sh

  macos:
    runs-on: macos-latest
    name: "ronin-install.sh on macOS"
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install shunit2
      - name: Configure env
        run: echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
      - name: Run tests
        run: ./test/ronin_install_test.sh
