name: CI

on:
  push:
    paths:
      - .github/workflows/ronin-dev.yml
      - Makefile
      - ronin-dev.sh
      - test/helper.sh
      - test/ronin_dev_test.sh
  pull_request:
    paths:
      - .github/workflows/ronin-dev.yml
      - Makefile
      - ronin-dev.sh
      - test/helper.sh
      - test/ronin_dev_test.sh

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    name: "ronin-dev on [${{ matrix.os }}]"
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y shunit2
        if: ${{ runner.os == 'Linux' }}
      - name: Install dependencies
        run: brew install wget shunit2
        if: ${{ runner.os == 'macOS' }}
      - name: Configure env
        run: echo "SHUNIT2=$(command -v shunit2 2>/dev/null)" >> $GITHUB_ENV
      - name: Run tests
        run: make test_dev
